name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip openjdk-11-jdk cmake autoconf automake libtool pkg-config
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer==1.5.0
        pip install kivy==2.1.0
        pip install pyjnius==1.4.2
    - name: Build APK
      run: |
        echo "y" | buildozer android debug
      continue-on-error: true
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: isan-language-app
        path: bin/*.apk
        if-no-files-found: ignore
