name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04  # Use newer Ubuntu version
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python3-dev python3-venv openjdk-11-jdk cmake autoconf automake libtool pkg-config
        
    - name: Install Python dependencies with specific versions
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install cython==0.29.36  # Specific version for compatibility
        pip install buildozer==1.5.0
        pip install kivy==2.1.0
        
    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        
        # Download Android command line tools
        cd $HOME/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        
        # Accept licenses automatically
        echo "y" | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        
        # Install required components
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        
        # Set environment variables
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'SPECEND'
[app]
title = Isaan Language Learning
package.name = isanlanguage
package.domain = org.isanlanguage
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,txt
version = 1.0
requirements = python3,kivy==2.1.0
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[app@android]
android.accept_sdk_license = True
android.arch = arm64-v8a  # Single architecture for faster build
android.api = 31
android.minapi = 21
SPECEND
        
    - name: Build APK with single architecture
      run: |
        # Set environment variables
        export ANDROID_HOME="$HOME/android-sdk"
        export ANDROID_SDK_ROOT="$HOME/android-sdk"
        
        # Build with single architecture (faster, less error-prone)
        timeout 60m buildozer android debug
      continue-on-error: true
      
    - name: Check for APK
      run: |
        echo "Checking for APK files..."
        find . -name "*.apk" -type f || echo "No APK files found"
        ls -la bin/ || echo "Bin directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: isan-language-app
        path: |
          bin/*.apk
          *.apk
        if-no-files-found: ignore
        retention-days: 30
