name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev openjdk-11-jdk cmake autoconf automake libtool pkg-config
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer==1.5.0 kivy==2.1.0
        
    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        echo "y" | buildozer android debug
      continue-on-error: true
      
    - name: Create buildozer.spec with single architecture
      run: |
        cat > buildozer.spec << 'SPECEND'
[app]
title = Isaan Language Learning
package.name = isanlanguage
package.domain = org.isanlanguage
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,txt
version = 1.0
requirements = python3,kivy==2.1.0
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[app@android]
android.accept_sdk_license = True
android.arch = arm64-v8a  # SINGLE ARCHITECTURE (faster, more reliable)
android.api = 31
android.minapi = 21
SPECEND
        
    - name: Build APK with single architecture
      run: |
        # Accept any remaining licenses
        echo "y" | buildozer android debug
      continue-on-error: true
      
    - name: Check for APK
      run: |
        echo "Checking for APK files..."
        find . -name "*.apk" -type f || echo "No APK files found"
        ls -la bin/ || echo "Bin directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: isan-language-app
        path: |
          bin/*.apk
          *.apk
        if-no-files-found: ignore
        retention-days: 30
