name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev openjdk-11-jdk
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython kivy==2.1.0
        
    - name: Accept Android SDK licenses
      run: |
        mkdir -p $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        echo "y" | buildozer android debug
      continue-on-error: true
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: isan-language-app
        path: bin/*.apk
        if-no-files-found: ignore
