name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python3-dev python3-venv openjdk-11-jdk
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython kivy==2.1.0
        
    - name: Create buildozer.spec if missing
      run: |
mkdir -p .github/workflows
cd ~/isan-language-app-fresh
ls -la
ls -la .github/workflows/
if [ -f ".github/workflows/build-android.yml" ]; then
    echo "✅ Workflow file exists"
    ls -la .github/workflows/build-android.yml
else
    echo "❌ Workflow file doesn't exist - need to create it"
fi
mkdir -p .github/workflows
cat > .github/workflows/build-android.yml << 'EOF'
name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python3-dev python3-venv openjdk-11-jdk
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython kivy==2.1.0
        
    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f "buildozer.spec" ]; then
          echo "[app]" > buildozer.spec
          echo "title = Isaan Language Learning" >> buildozer.spec
          echo "package.name = isanlanguage" >> buildozer.spec
          echo "package.domain = org.isanlanguage" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,png,jpg,kv,atlas,json,txt" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy==2.1.0" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
          echo "fullscreen = 0" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = 2" >> buildozer.spec
          echo "" >> buildozer.spec
          echo "[app@android]" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "android.arch = arm64-v8a" >> buildozer.spec
          echo "android.api = 31" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
        fi
        
    - name: Build APK
      run: |
        buildozer android debug
      continue-on-error: true
      
    - name: Upload APK
      uses: actions/upload-artifact@v4  # v4 - not deprecated!
      with:
        name: isan-language-app
        path: bin/*.apk
        if-no-files-found: ignore
        retention-days: 30
