name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip libffi-dev libssl-dev openjdk-11-jdk cmake autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install cython==0.29.36
        pip install buildozer==1.5.0
        pip install kivy==2.1.0
        pip install pyjnius==1.6.1
        
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'SPECEND'
[app]
title = Isaan Language Learning
package.name = isanlanguage
package.domain = org.isanlanguage
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,txt
version = 1.0
requirements = python3,kivy==2.1.0,pyjnius==1.6.1
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[app@android]
android.accept_sdk_license = True
android.arch = arm64-v8a
android.api = 33
android.minapi = 21
android.ndk = 25b
android.sdk = 33
SPECEND
        
    - name: Build APK
      run: |
        timeout 60m buildozer android debug
      continue-on-error: true
      
    - name: Check for APK
      run: |
        echo "Checking for APK files..."
        find . -name "*.apk" -type f || echo "No APK files found"
        ls -la bin/ || echo "Bin directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: isan-language-app
        path: |
          bin/*.apk
          *.apk
        if-no-files-found: ignore
        retention-days: 30
